# Generated by Django 4.2 on 2023-04-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(default='https://picsum.photos/200/300', max_length=200),
        ),
    ]
